server:
  port: 8080

spring:
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/board?currentSchema=public
    username: postgres
    password: root123
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate.ddl-auto: update
    show-swl: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always # always-init data loading, never-init data not loading
